trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(DOCKER_REPOSITORY_NAME)
      command: build
      Dockerfile: app/Dockerfile

  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'AWS_TEST'
      regionName: $(AWS_REGION)
      imageSource: 'imagename'
      sourceImageName: $(DOCKER_REPOSITORY_NAME)
      sourceImageTag: $(Build.BuildId)
      pushTag: latest
      repositoryName: $(DOCKER_REPOSITORY_NAME)
