trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      command: build
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      repository: $(DOCKER_REPOSITORY_NAME)

  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'AWS_TEST'
      regionName: $(AWS_REGION)
      imageSource: 'imagename'
      sourceImageName: $(DOCKER_REPOSITORY_NAME)
      sourceImageTag: $(Build.BuildId)
      pushTag: latest
      repositoryName: $(DOCKER_REPOSITORY_NAME)
